#FileName: costmap_common_params.yaml
#Author: leo
#Description:
# 代价地图通用参数配置文件,就是全局代价地图和局部代价地图
# 共同都需要配置的参数,各参数意义如下:
#
#History:
# 20180613: initial this file.
footprint: [[-0.24, 0.20], [0.24, 0.20],[0.24, -0.20],[-0.24, -0.20]]

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true #允许规划到未知区域
  obstacle_range: 2.5 #2.5以内的障碍物，才被引入到代价地图中
  raytrace_range: 3.0 #在3.0米以内，根据扫描数据清除先前引入的障碍物
  observation_sources: laser_scan_sensor 
  laser_scan_sensor: 
    sensor_frame: laser
    data_type: LaserScan
    topic: scan
    marking: true #是否允许传感器向代价地图添加障碍物
    clearing: true #是否允许传感器从代价地图清楚障碍物
    min_obstacle_height: 0.25 #最低障碍物
    max_obstacle_height: 0.60 #最高障碍物  名字起得不好，本意是对传感器数据在z轴上进行剪裁，应该起名为min/max_scan_height.此范围应该包括激光雷达高度h（即设定的tf）

inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0 #决定了cost往外膨胀时递减的快慢程度
  inflation_radius: 0.36 #代价从内切半径处开始往外扩散（以负指数的形式）

static_layer:
  enabled: true
